spring:
#  datasource:
#    url: jdbc:postgresql://perfectly-prompt-egret.a1.pgedge.io:5432/tripbyday?sslmode=require
#    username: app
#    password: 6qrn9Oi48IbI2oQl48Be615v
#    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:postgresql://localhost:5432/SaiGonByDay
#    username: postgres
#    password: sa
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://ep-rough-band-a15zq7c8.ap-southeast-1.aws.neon.tech/tripbyday?sslmode=require
    username: tripbyday_owner
    password: UaoN7uglL9jF
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8081